
version: 2
jobs:
  build:
    context: org-global
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: |
            sudo npm install -g yarn
            yarn install
      - save-cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Running tests
      - run:
          name: Deploying
          command: |
            DEPLOY_URL=$(./node_modules/.bin/now -t ${NOW_CLI_TOKEN})
            ./node_modules/.bin/now alias whatisthisintouch.now.sh